include:
  - project: repositories/hardware-scripts
    ref: main
    file: ci_templates/.ci_python_w_docs.yml

test:
  stage: test
  image: 'debian:bookworm'
  before_script:
    - export PATH=$HOME/.local/bin:$PATH
    - mkdir -p logs
    - echo 'deb http://deb.debian.org/debian bookworm-backports main' > /etc/apt/sources.list.d/backports.list
    - apt-get -qqy update >> logs/debian_install.log
    - apt-get -qqy update --fix-missing >> logs/debian_install.log
    - apt update && apt -qqy install git pip python3-poetry gerbv inkscape python3.11 pipx >> logs/debian_install.log
    - apt-get -qqy install -t bookworm-backports kicad >> logs/debian_install.log
    - python3.11 -m pipx install 'git+https://github.com/antmicro/gerber2blend.git'
    - python3.11 -m pipx install .
    - python3.11 -m pip install 'git+https://github.com/antmicro/kicad-make.git' --break-system-packages
    - git clone --quiet https://github.com/antmicro/environment-sensor.git
    - git clone --quiet https://github.com/antmicro/hardware-components.git --depth=1
  script:
    - export PATH=$HOME/.local/bin:$PATH
    - export MODEL_LIBRARY_PATHS=$PWD/hardware-components/
    - cd environment-sensor
    - mkdir fab
    - kicad-cli pcb export gerbers --no-protel-ext -o fab/ environment-sensor.kicad_pcb
    - kicad-cli pcb export drill --format gerber --excellon-separate-th -o fab/ environment-sensor.kicad_pcb
    - kmake bom
    - kmake bom --dnp
    - kmake pnp
    - gerber2blend
    - picknblend
  artifacts:
    paths:
      - environment-sensor/assets
      - environment-sensor/doc
      - environment-sensor/img
      - environment-sensor/fab
      - environment-sensor/*.kicad*
      - environment-sensor/sym-lib-table
      - environment-sensor/fp-lib-table
      - environment-sensor/README.md
      - environment-sensor/LICENSE
      - environment-sensor/blendcfg.yaml

